---
title: "bdb_analysis_V8"
date: "2024-07-31"
author: "Ravinder Singh"
output:
  html_document:
    code_folding: hide
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE, warning = FALSE, message = FALSE)
```

```{r}
library(ggplot2)
library(dplyr)
```

# This analysis is aimed to analyze the results that are obtained in 'bdb_analysis_V7' in a file named "all_results".

```{r}
load("H:/ravi_dsi_summer_project/bdb_analysis_V7/all_results_100_1-5.RData")
```

```{r}
num_reps <- 5
num_het_conds <- 4
num_prior_sets <- 8
num_vars <- 7
```

```{r}
results_df <- expand.grid(1:num_vars, 1:num_prior_sets, 1:num_reps, 1:num_het_conds)
names(results_df) <- c("Variable_Name", "Prior_Setting", "Replicates", "Heterogeneity_Level")
results_df <- results_df |>
  dplyr::select("Heterogeneity_Level", "Replicates", "Prior_Setting", "Variable_Name")
```

```{r}
results_df <- results_df |>
  mutate(Heterogeneity_Level = case_when(Heterogeneity_Level==1~2,
                                         Heterogeneity_Level==2~5,
                                         Heterogeneity_Level==3~8,
                                         Heterogeneity_Level==4~10))

results_df <- results_df |>
  mutate(Heterogeneity_Level_Name = case_when(Heterogeneity_Level==2~"50% less",
                                              Heterogeneity_Level==5~"Same",
                                              Heterogeneity_Level==8~"50% more",
                                              Heterogeneity_Level==10~"Opposite"))

results_df <- results_df |>
  mutate(Variable_Name = case_when(Variable_Name==1~"Intercept",
                                   Variable_Name==2~"Age",
                                   Variable_Name==3~"Female",
                                   Variable_Name==4~"BMI",
                                   Variable_Name==5~"Liver_Mets",
                                   Variable_Name==6~"Hepatic_Imp",
                                   Variable_Name==7~"Num_Mets_MoreThan2"))

results_df <- results_df |>
  mutate(Prior_Setting = case_when(Prior_Setting==1~"Complete Pooling",
                                   Prior_Setting==2~"Non-Informative",
                                   Prior_Setting==3~"PP(0)",
                                   Prior_Setting==4~"PP(0.5)",
                                   Prior_Setting==5~"PP(1)",
                                   Prior_Setting==6~"BDB(0.1, 0.1)",
                                   Prior_Setting==7~"BDB(1, 1)",
                                   Prior_Setting==8~"BDB(1, 0.1)"))

results_df <- results_df |>
  dplyr::select("Heterogeneity_Level_Name", "Heterogeneity_Level", "Replicates",
                "Prior_Setting", "Variable_Name")
```

```{r}
# Let's modify our 'all_results' list.

split_all_results <- split(all_results, ceiling(seq_along(all_results)/num_reps))
```

Now, let's fill in all the results from 'all_results' to 'results_df'.

```{r}
TESS <- NULL
looic <- NULL
log.MSE <- NULL
per.bias <- NULL
width_hpd_95 <- NULL
coverage_95 <- NULL

for (i in 1:num_het_conds) {
  for (j in 1:num_reps){
    a <- split_all_results[[i]][[j]]
    
    TESS <- c(TESS, c(a$pool_TESS, a$non_inf_TESS, a$pp.0_TESS, a$pp.50_TESS,
                      a$pp.1_TESS, a$bdb_.1_TESS, a$bdb_1_1_TESS, a$bdb_1_.1_TESS))
    
    looic <- c(looic, c(rep(a$pool_looic[2], num_vars), 
                        rep(a$non_inf_looic[2], num_vars),
                        rep(a$pp.0_looic[2], num_vars),
                        rep(a$pp.50_looic[2], num_vars),
                        rep(a$pp.1_looic[2], num_vars),
                        rep(a$bdb_.1_looic[2], num_vars),
                        rep(a$bdb_1_1_looic[2], num_vars),
                        rep(a$bdb_1_.1_looic[2], num_vars)))
    
    log.MSE <- c(log.MSE, c(a$pool_log.MSE[1:7], a$non_inf_log.MSE[1:7], a$pp.0_log.MSE[1:7],
                            a$pp.50_log.MSE[1:7], a$pp.1_log.MSE[1:7], a$bdb_.1_log.MSE[1:7],
                            a$bdb_1_1_log.MSE[1:7], a$bdb_1_.1_log.MSE[1:7]))
    
    per.bias <- c(per.bias, c(a$pool_per.bias[1:7], a$non_inf_per.bias[1:7], a$pp.0_per.bias[1:7],
                              a$pp.50_per.bias[1:7], a$pp.1_per.bias[1:7], a$bdb_.1_per.bias[1:7],
                              a$bdb_1_1_per.bias[1:7], a$bdb_1_.1_per.bias[1:7]))
    
    width_hpd_95 <- c(width_hpd_95, c(a$pool_width_hpd_95 |> as.numeric(),
                                      a$non_inf_width_hpd_95 |> as.numeric(),
                                      a$pp.0_width_hpd_95 |> as.numeric(),
                                      a$pp.50_width_hpd_95 |> as.numeric(),
                                      a$pp.1_width_hpd_95 |> as.numeric(),
                                      a$bdb_.1_width_hpd_95 |> as.numeric(),
                                      a$bdb_1_1_width_hpd_95 |> as.numeric(),
                                      a$bdb_1_.1_width_hpd_95 |> as.numeric()))
    
    coverage_95 <- c(coverage_95, c(a$pool_coverage_95, a$non_inf_coverage_95,
                                    a$pp.0_coverage_95, a$pp.50_coverage_95,
                                    a$pp.1_coverage_95, a$bdb_.1_coverage_95,
                                    a$bdb_1_1_coverage_95, a$bdb_1_.1_coverage_95))
    
  }
}

results_df <- results_df |>
  mutate(TESS = TESS,
         looic = looic,
         log.MSE = log.MSE,
         per.bias = per.bias,
         width_hpd_95 = width_hpd_95,
         coverage_95 = coverage_95)
```

```{r}
avg_results_df <- results_df |>
  group_by(Heterogeneity_Level_Name, Prior_Setting, Variable_Name) |>
  summarise(mean_TESS = mean(TESS),
            mean_looic = mean(looic),
            mean_log.MSE = mean(log.MSE),
            mean_per.bias = mean(per.bias),
            mean_width_hpd_95 = mean(width_hpd_95),
            mean_coverage_95 = mean(coverage_95))
```

```{r}
avg_results_df <- avg_results_df |>
  mutate(Heterogeneity_Level_Name = factor(Heterogeneity_Level_Name,
                                           levels = c("50% less", "Same", "50% more", "Opposite"),
                                           labels = c("50% less", "Same", "50% more", "Opposite")),
         
         Variable_Name = factor(Variable_Name,
                                levels = c("Intercept", "Age", "Female", "BMI", "Liver_Mets",
                                           "Hepatic_Imp", "Num_Mets_MoreThan2"),
                                labels = c("Intercept", "Age", "Female", "BMI", "Liver_Mets",
                                           "Hepatic_Imp", "Num_Mets_MoreThan2")),
         
         Prior_Setting = factor(Prior_Setting,
                                levels = c("Complete Pooling", "Non-Informative",
                                           "PP(0)", "PP(0.5)", "PP(1)",
                                           "BDB(0.1, 0.1)", "BDB(1, 1)", "BDB(1, 0.1)"),
                                labels = c("Complete Pooling", "Non-Informative",
                                           "PP(0)", "PP(0.5)", "PP(1)",
                                           "BDB(0.1, 0.1)", "BDB(1, 1)", "BDB(1, 0.1)")))
```

```{r}
avg_results_df <- avg_results_df |>
  mutate(Prior_Setting_Class = case_when(Prior_Setting %in% c("Complete Pooling") ~ "Comp-Pool",
                                         Prior_Setting %in% c("Non-Informative") ~ "Non-Inf",
                                         Prior_Setting %in% c("PP(0)", "PP(0.5)", "PP(1)") ~ "PP",
                                         Prior_Setting %in% c("BDB(0.1, 0.1)", "BDB(1, 1)", "BDB(1, 0.1)") ~ "BDB"))

avg_results_df <- avg_results_df |>
  mutate(Prior_Setting_Class = factor(Prior_Setting_Class,
                                      levels = c("Comp-Pool", "Non-Inf", "PP", "BDB")))
```


# Now, let's plot some stuff.

For, mean_looic

```{r}
ggplot(avg_results_df, aes(x = Heterogeneity_Level_Name, y = mean_looic, group = Prior_Setting, color = Prior_Setting)) +
  geom_line() +
  facet_grid(.~Prior_Setting_Class) +
  labs(title = "2x2 Grid Plot",
       x = "X-Axis Label",
       y = "Y-Axis Label",
       linetype = "Group") +
  theme_minimal()
```

For, mean_TESS

```{r}
ggplot(avg_results_df, aes(x = Heterogeneity_Level_Name, y = mean_TESS, group = Prior_Setting, color = Prior_Setting)) +
  geom_line() +
  facet_grid(Variable_Name ~ Prior_Setting_Class) +
  labs(title = "2x2 Grid Plot",
       x = "X-Axis Label",
       y = "Y-Axis Label",
       linetype = "Group") +
  theme_minimal()
```

For, mean_log.MSE

```{r}
ggplot(avg_results_df, aes(x = Heterogeneity_Level_Name, y = mean_log.MSE, group = Prior_Setting, color = Prior_Setting)) +
  geom_line() +
  facet_grid(Variable_Name ~ Prior_Setting_Class) +
  labs(title = "2x2 Grid Plot",
       x = "X-Axis Label",
       y = "Y-Axis Label",
       linetype = "Group") +
  theme_minimal()
```

For, mean_per.bias

```{r}
ggplot(avg_results_df, aes(x = Heterogeneity_Level_Name, y = mean_per.bias, group = Prior_Setting, color = Prior_Setting)) +
  geom_line() +
  facet_grid(Variable_Name ~ Prior_Setting_Class) +
  labs(title = "2x2 Grid Plot",
       x = "X-Axis Label",
       y = "Y-Axis Label",
       linetype = "Group") +
  theme_minimal()
```

For, mean_width_hpd_95

```{r}
ggplot(avg_results_df, aes(x = Heterogeneity_Level_Name, y = mean_width_hpd_95, group = Prior_Setting, color = Prior_Setting)) +
  geom_line() +
  facet_grid(Variable_Name ~ Prior_Setting_Class) +
  labs(title = "2x2 Grid Plot",
       x = "X-Axis Label",
       y = "Y-Axis Label",
       linetype = "Group") +
  theme_minimal()
```

For, mean_coverage_95

```{r}
ggplot(avg_results_df, aes(x = Heterogeneity_Level_Name, y = mean_coverage_95, group = Prior_Setting, color = Prior_Setting)) +
  geom_line() +
  facet_grid(Variable_Name ~ Prior_Setting_Class) +
  labs(title = "2x2 Grid Plot",
       x = "X-Axis Label",
       y = "Y-Axis Label",
       linetype = "Group") +
  theme_minimal()
```

```{r}

```

